apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-service
spec:
  selector:
    app: broidery-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 31000
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 192.0.2.127
